# Generated by Django 3.1.2 on 2020-11-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
