# Generated by Django 3.1.2 on 2020-11-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='template_location',
        ),
    ]
