# Generated by Django 3.1.2 on 2020-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0002_remove_question_template_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_num',
            new_name='num',
        ),
        migrations.AddField(
            model_name='question',
            name='template_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='internal_name',
            field=models.CharField(max_length=50),
        ),
    ]
