# Generated by Django 3.1.2 on 2020-11-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0004_auto_20201126_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='display_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
