# Generated by Django 3.1.2 on 2020-11-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0005_questiontemplate_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='num',
            new_name='number',
        ),
    ]
