# Generated by Django 3.1.2 on 2020-11-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0007_auto_20201127_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(),
        ),
    ]
