# Generated by Django 3.1.2 on 2020-11-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0008_auto_20201127_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('internal_name', models.CharField(max_length=50)),
                ('template_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='internal_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='template_name',
        ),
        migrations.AddField(
            model_name='question',
            name='question_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='worksheet.questiontemplate'),
            preserve_default=False,
        ),
    ]
