# Generated by Django 3.1.2 on 2020-11-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        ('worksheet', '0009_auto_20201127_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='WorksheetQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionTemplate',
        ),
        migrations.AlterField(
            model_name='worksheetquestion',
            name='question_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questiontemplate'),
        ),
    ]
